### ISSUE TITLE
Feature: User can view a list of recipes

### ISSUE THREAD

**Issue by mioriimai** [miori-i/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of recipes.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Display home view and by clicking "see recipes →" or "recipes" on navber, it shows the list of all recipes.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="914" alt="Screen Shot 2022-11-17 at 2 22 35" src="https://user-images.githubusercontent.com/54726911/202249953-cb3095d3-947e-43ac-84eb-1cd7f7355918.png">
<img width="744" alt="Screen Shot 2022-11-17 at 2 23 43" src="https://user-images.githubusercontent.com/54726911/202250148-07f58043-aa40-4f2d-b24f-01f9f3546164.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a div[data-view="home"] to the HTML.
- [x] Add an image and text and CSS styling for the home view.
- [x] Ensure that the home view looks nice on both mobile-sized and desktop-sized screens.
- [x] Add a div[data-view="all-recipes"] to the HTML.
- [x] Add an empty unordered list to the [data-view="all-recipes"] element.
- [x] Add some dummy recipes to the unorderedlist in the HTML and style them to match the wireframe.
- [x] Check that the recipes list looks good on both mobile and desktop screens.
- [x] Get the date that will be shown in all recipes view from API and push them to the empty array allRecipes.
- [x] Define a function that takes a single recipe object and returns a DOM tree that matches one of the example entries in the HTML.
- [x] Use a loop to create a DOM tree for each recipe in the data model and append it to the page.
- [x] Remove the example HTML entries once the recipes are successfully being appended to the DOM on page load.
- [x] Add a navigation item to the navbar for home and all-recipes.
- [x] Add an anchor to the home view and all-recipes view.
- [x] Add a click target for navber.
- [x] Add a click target for button "see recipes→".
- [x] Ensure that refreshing the pages shows the same view as before refreshing.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
