### ISSUE TITLE
Feature: User can view the details of a recipe

### ISSUE THREAD

**Issue by mioriimai** [miori-i/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the details of a recipe.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="410" alt="image" src="https://user-images.githubusercontent.com/54726911/202255937-9b159a9f-b65f-4465-8f05-1ad5a1b5d292.png">
<img width="230" alt="image" src="https://user-images.githubusercontent.com/54726911/202256086-54484490-e963-46d5-9381-d35b87c89f03.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a sibling div[data-view="recipe-details"] to the HTML.
- [x] Add a dummy recipe with details to the HTML and style it to match the wireframe.
- [x] Check that a recipe with details looks good on both mobile and desktop screens.
- [x] Listen for clicks on the parent element of all rendered recipes in all recipes view.
- [x] Show the recipe details view if a recipe in the all recipes view was clicked.
- [x] Aassign the clicked object to the data model's view-details property if an recipe in the all recipes view was clicked.
- [x] Refreshing the pages shows the same view as before refreshing
- [x] Clear the values up when user leave all recipes view.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
