### ISSUE TITLE
Feature: User can save a recipe to their favorites list

### ISSUE THREAD

**Issue by mioriimai** [miori-i/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="886" alt="image" src="https://user-images.githubusercontent.com/54726911/202256440-409629e2-5543-47b6-80ed-2d4d6a3509aa.png">
<img width="725" alt="image" src="https://user-images.githubusercontent.com/54726911/202256557-9c968366-ffd8-44c4-a1d2-39f26973c5db.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a star icon to the image of the recipe details view
- [x] Listen for clicks on the star icon and copy the info of the recipe to favorites of the data modal and change the color of the star icon.
- [x] Check that looks good on both mobile and desktop screens.
- [x] Add a sibling div[data-view="favourites"] to the HTML.
- [x] Use a loop to create a DOM tree for each recipe of the favorites list and append it to the page.
- [x] Listen for clicks on the parent element of all rendered recipes in favorites view to see the details of the clicked recipe.
- [x] Update viewSwapping function.
- [x] Make sure that the recipe that is already in the favorites list won't be added to the favorites list again.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
