### ISSUE TITLE
Feature: User can add comments on a recipe

### ISSUE THREAD

**Issue by mioriimai** [miori-i/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="620" alt="image" src="https://user-images.githubusercontent.com/54726911/202256790-6fb3c80a-9b3f-45ee-a3ad-8dc615817917.png">
<img width="386" alt="image" src="https://user-images.githubusercontent.com/54726911/202256889-facf2f8f-5618-4cc1-b945-56e8853c4cef.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a form for creating a comment to the div[data-view="recipe-details"] in the HTML.
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x] Listen for 'submit' events on the comment form and:
  - [x] Put the form's input values into a new object.
  - [x] Append the new object to comments in the data model.
- [x] Add some dummy conversations to the unordered list in the HTML and style them to match the wireframe.
- [x] Define a function that takes a single comment object and returns a DOM tree that matches one of the example entries in the HTML.
  - [x] Make sure the number of comments will be updated. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
