### ISSUE TITLE
Feature: User can filter recipes by type of cuisine

### ISSUE THREAD

**Issue by mioriimai** [miori-i/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="916" alt="image" src="https://user-images.githubusercontent.com/54726911/202257215-0422112e-21df-43e3-99bb-0ae6a15d0497.png">
<img width="860" alt="image" src="https://user-images.githubusercontent.com/54726911/202257328-f1a224d1-84fa-4d2d-986e-f3996602a49b.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add drop-down boxes to the all recipes view on the HTML.
- [x] Check that looks good on both mobile and desktop screens. 
- [x] Listen for "change" events on the drop-down boxes and:
  - [x] Show the recipes that its type of cuisine is equal to the selected one. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
